In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/kyc_data.csv')
print(df.head())

   recordid datasource firstinitial firstname middlename lastname dayofbirth  \
0  record_1          a        match     match      match      NaN      match
1  record_1          b        match     match      match    match      match
2  record_1          c        match     match      match    match      match
3  record_1          d      nomatch     match      match  nomatch      match
4  record_1          e        match   nomatch      match    match    nomatch

  monthofbirth yearofbirth streetname  ...   city   region postalcode  \
0        match       match      match  ...    NaN    match      match
1      missing     missing      match  ...  match    match      match
2        match       match      match  ...  match  nomatch    nomatch
3        match     nomatch      match  ...  match  nomatch    nomatch
4        match     nomatch      match  ...  match  nomatch      match

  unitnumber address1    taxid socialinsurancenumber  voterid   gender  \
0      match      NaN  nomatch               nomatch  nomatch    match
1      match    match    match               nomatch    match    match
2    missing    match    match                 match    match  missing
3      match  nomatch  missing                 match  nomatch  nomatch
4      match  nomatch  nomatch                 match  nomatch    match

  trumatch_confidence
0            0.553762
1            0.568361
2            0.501050
3            0.808702
4            0.536946

[5 rows x 22 columns]

In [3]:
df

,recordid,datasource,firstinitial,firstname,middlename,lastname,dayofbirth,monthofbirth,yearofbirth,streetname,...,city,region,postalcode,unitnumber,address1,taxid,socialinsurancenumber,voterid,gender,trumatch_confidence
0,record_1,a,match,match,match,NaN,match,match,match,match,...,NaN,match,match,match,NaN,nomatch,nomatch,nomatch,match,0.553762
1,record_1,b,match,match,match,match,match,missing,missing,match,...,match,match,match,match,match,match,nomatch,match,match,0.568361
2,record_1,c,match,match,match,match,match,match,match,match,...,match,nomatch,nomatch,missing,match,match,match,match,missing,0.501050
3,record_1,d,nomatch,match,match,nomatch,match,match,nomatch,match,...,match,nomatch,nomatch,match,nomatch,missing,match,nomatch,nomatch,0.808702
4,record_1,e,match,nomatch,match,match,nomatch,match,nomatch,match,...,match,nomatch,match,match,nomatch,nomatch,match,nomatch,match,0.536946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,record_999,d,match,match,match,match,match,match,match,match,...,match,match,match,match,match,match,match,match,nomatch,0.566787
7996,record_999,e,nomatch,match,missing,match,match,nomatch,match,nomatch,...,match,match,match,match,match,match,match,nomatch,match,0.554050
7997,record_999,f,nomatch,match,missing,match,nomatch,match,match,match,...,nomatch,match,missing,nomatch,match,match,match,nomatch,match,0.470194
7998,record_999,g,nomatch,nomatch,NaN,NaN,matcha,matcha,matcha,matcha,...,NaN,nomatch,NaN,matcha,matcha,nomatch,match,match,nomatch,0.689957
7999,record_999,h,match,missing,missing,nomatch,nomatch,nomatch,missing,nomatch,...,nomatch,match,nomatch,nomatch,match,nomatch,match,nomatch,missing,0.741251

In [4]:
df.columns

Index(['recordid', 'datasource', 'firstinitial', 'firstname', 'middlename',
       'lastname', 'dayofbirth', 'monthofbirth', 'yearofbirth', 'streetname',
       'streetnumber', 'streettype', 'city', 'region', 'postalcode',
       'unitnumber', 'address1', 'taxid', 'socialinsurancenumber', 'voterid',
       'gender', 'trumatch_confidence'],
      dtype='str')

In [5]:
df_match_field = [ 'firstinitial', 'firstname', 'middlename',
       'lastname', 'dayofbirth', 'monthofbirth', 'yearofbirth', 'streetname',
       'streetnumber', 'streettype', 'city', 'region', 'postalcode',
       'unitnumber', 'address1', 'taxid', 'socialinsurancenumber', 'voterid',
       'gender']

In [6]:
set(df[df_match_field].values.flatten())

{'match', 'matcha', 'missing', nan, 'nomatch'}

In [7]:
df.replace('matcha', 'match', inplace=True)
df.replace(np.nan, 'unknown', inplace=True)

,recordid,datasource,firstinitial,firstname,middlename,lastname,dayofbirth,monthofbirth,yearofbirth,streetname,...,city,region,postalcode,unitnumber,address1,taxid,socialinsurancenumber,voterid,gender,trumatch_confidence
0,record_1,a,match,match,match,unknown,match,match,match,match,...,unknown,match,match,match,unknown,nomatch,nomatch,nomatch,match,0.553762
1,record_1,b,match,match,match,match,match,missing,missing,match,...,match,match,match,match,match,match,nomatch,match,match,0.568361
2,record_1,c,match,match,match,match,match,match,match,match,...,match,nomatch,nomatch,missing,match,match,match,match,missing,0.501050
3,record_1,d,nomatch,match,match,nomatch,match,match,nomatch,match,...,match,nomatch,nomatch,match,nomatch,missing,match,nomatch,nomatch,0.808702
4,record_1,e,match,nomatch,match,match,nomatch,match,nomatch,match,...,match,nomatch,match,match,nomatch,nomatch,match,nomatch,match,0.536946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,record_999,d,match,match,match,match,match,match,match,match,...,match,match,match,match,match,match,match,match,nomatch,0.566787
7996,record_999,e,nomatch,match,missing,match,match,nomatch,match,nomatch,...,match,match,match,match,match,match,match,nomatch,match,0.554050
7997,record_999,f,nomatch,match,missing,match,nomatch,match,match,match,...,nomatch,match,missing,nomatch,match,match,match,nomatch,match,0.470194
7998,record_999,g,nomatch,nomatch,unknown,unknown,match,match,match,match,...,unknown,nomatch,unknown,match,match,nomatch,match,match,nomatch,0.689957
7999,record_999,h,match,missing,missing,nomatch,nomatch,nomatch,missing,nomatch,...,nomatch,match,nomatch,nomatch,match,nomatch,match,nomatch,missing,0.741251

In [8]:
set(df[df_match_field].values.flatten())

{'match', 'missing', 'nomatch', 'unknown'}

In [9]:
df.sort_values('recordid', ascending=True)

,recordid,datasource,firstinitial,firstname,middlename,lastname,dayofbirth,monthofbirth,yearofbirth,streetname,...,city,region,postalcode,unitnumber,address1,taxid,socialinsurancenumber,voterid,gender,trumatch_confidence
0,record_1,a,match,match,match,unknown,match,match,match,match,...,unknown,match,match,match,unknown,nomatch,nomatch,nomatch,match,0.553762
1,record_1,b,match,match,match,match,match,missing,missing,match,...,match,match,match,match,match,match,nomatch,match,match,0.568361
2,record_1,c,match,match,match,match,match,match,match,match,...,match,nomatch,nomatch,missing,match,match,match,match,missing,0.501050
3,record_1,d,nomatch,match,match,nomatch,match,match,nomatch,match,...,match,nomatch,nomatch,match,nomatch,missing,match,nomatch,nomatch,0.808702
4,record_1,e,match,nomatch,match,match,nomatch,match,nomatch,match,...,match,nomatch,match,match,nomatch,nomatch,match,nomatch,match,0.536946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,record_999,d,match,match,match,match,match,match,match,match,...,match,match,match,match,match,match,match,match,nomatch,0.566787
7996,record_999,e,nomatch,match,missing,match,match,nomatch,match,nomatch,...,match,match,match,match,match,match,match,nomatch,match,0.554050
7997,record_999,f,nomatch,match,missing,match,nomatch,match,match,match,...,nomatch,match,missing,nomatch,match,match,match,nomatch,match,0.470194
7998,record_999,g,nomatch,nomatch,unknown,unknown,match,match,match,match,...,unknown,nomatch,unknown,match,match,nomatch,match,match,nomatch,0.689957
7999,record_999,h,match,missing,missing,nomatch,nomatch,nomatch,missing,nomatch,...,nomatch,match,nomatch,nomatch,match,nomatch,match,nomatch,missing,0.741251

In [10]:
df.recordid.value_counts().value_counts()

count
8    1000
Name: count, dtype: int64

In [11]:
len(set(df.recordid))

1000

In [12]:
df = pd.read_csv('../data/kyc_data.csv')
df.drop_duplicates(inplace=True)
df_match_field = [ 'firstinitial', 'firstname', 'middlename',
       'lastname', 'dayofbirth', 'monthofbirth', 'yearofbirth', 'streetname',
       'streetnumber', 'streettype', 'city', 'region', 'postalcode',
       'unitnumber', 'address1', 'taxid', 'socialinsurancenumber', 'voterid',
       'gender']
print(set(df[df_match_field].values.flatten()))
df.replace('matcha', 'match', inplace=True)
df.replace(np.nan, 'unknown', inplace=True)
df.recordid.value_counts().value_counts()

{'missing', nan, 'nomatch', 'matcha', 'match'}

count
8    1000
Name: count, dtype: int64

In [13]:
import sys
from pathlib import Path
import pickle

# add repo root to python path
sys.path.append(str(Path().resolve().parent))

import core.models as Models
import core.engine_processor as Engine

In [14]:
with open("../data/records.pkl", "rb") as f:
    records = pickle.load(f)

In [15]:
len(records)

1000

In [16]:
record = records[0]
record.record_id

'record_1'

In [17]:
record

RecordEntry(record_id='record_1', datasources={'a': DataSourceResult(datasource_id='a', fields={'firstinitial': <MatchFieldState.MATCH: 'match'>, 'firstname': <MatchFieldState.MATCH: 'match'>, 'middlename': <MatchFieldState.MATCH: 'match'>, 'lastname': <MatchFieldState.UNKNOWN: 'unknown'>, 'dayofbirth': <MatchFieldState.MATCH: 'match'>, 'monthofbirth': <MatchFieldState.MATCH: 'match'>, 'yearofbirth': <MatchFieldState.MATCH: 'match'>, 'streetname': <MatchFieldState.MATCH: 'match'>, 'streetnumber': <MatchFieldState.MATCH: 'match'>, 'streettype': <MatchFieldState.MATCH: 'match'>, 'city': <MatchFieldState.UNKNOWN: 'unknown'>, 'region': <MatchFieldState.MATCH: 'match'>, 'postalcode': <MatchFieldState.MATCH: 'match'>, 'unitnumber': <MatchFieldState.MATCH: 'match'>, 'address1': <MatchFieldState.UNKNOWN: 'unknown'>, 'taxid': <MatchFieldState.NOMATCH: 'nomatch'>, 'socialinsurancenumber': <MatchFieldState.NOMATCH: 'nomatch'>, 'voterid': <MatchFieldState.NOMATCH: 'nomatch'>, 'gender': <MatchFieldState.MATCH: 'match'>}, confidence=np.float64(0.5537621544721605)), 'b': DataSourceResult(datasource_id='b', fields={'firstinitial': <MatchFieldState.MATCH: 'match'>, 'firstname': <MatchFieldState.MATCH: 'match'>, 'middlename': <MatchFieldState.MATCH: 'match'>, 'lastname': <MatchFieldState.MATCH: 'match'>, 'dayofbirth': <MatchFieldState.MATCH: 'match'>, 'monthofbirth': <MatchFieldState.MISSING: 'missing'>, 'yearofbirth': <MatchFieldState.MISSING: 'missing'>, 'streetname': <MatchFieldState.MATCH: 'match'>, 'streetnumber': <MatchFieldState.MATCH: 'match'>, 'streettype': <MatchFieldState.MATCH: 'match'>, 'city': <MatchFieldState.MATCH: 'match'>, 'region': <MatchFieldState.MATCH: 'match'>, 'postalcode': <MatchFieldState.MATCH: 'match'>, 'unitnumber': <MatchFieldState.MATCH: 'match'>, 'address1': <MatchFieldState.MATCH: 'match'>, 'taxid': <MatchFieldState.MATCH: 'match'>, 'socialinsurancenumber': <MatchFieldState.NOMATCH: 'nomatch'>, 'voterid': <MatchFieldState.MATCH: 'match'>, 'gender': <MatchFieldState.MATCH: 'match'>}, confidence=np.float64(0.5683607492901042)), 'c': DataSourceResult(datasource_id='c', fields={'firstinitial': <MatchFieldState.MATCH: 'match'>, 'firstname': <MatchFieldState.MATCH: 'match'>, 'middlename': <MatchFieldState.MATCH: 'match'>, 'lastname': <MatchFieldState.MATCH: 'match'>, 'dayofbirth': <MatchFieldState.MATCH: 'match'>, 'monthofbirth': <MatchFieldState.MATCH: 'match'>, 'yearofbirth': <MatchFieldState.MATCH: 'match'>, 'streetname': <MatchFieldState.MATCH: 'match'>, 'streetnumber': <MatchFieldState.MATCH: 'match'>, 'streettype': <MatchFieldState.MATCH: 'match'>, 'city': <MatchFieldState.MATCH: 'match'>, 'region': <MatchFieldState.NOMATCH: 'nomatch'>, 'postalcode': <MatchFieldState.NOMATCH: 'nomatch'>, 'unitnumber': <MatchFieldState.MISSING: 'missing'>, 'address1': <MatchFieldState.MATCH: 'match'>, 'taxid': <MatchFieldState.MATCH: 'match'>, 'socialinsurancenumber': <MatchFieldState.MATCH: 'match'>, 'voterid': <MatchFieldState.MATCH: 'match'>, 'gender': <MatchFieldState.MISSING: 'missing'>}, confidence=np.float64(0.5010497195939172)), 'd': DataSourceResult(datasource_id='d', fields={'firstinitial': <MatchFieldState.NOMATCH: 'nomatch'>, 'firstname': <MatchFieldState.MATCH: 'match'>, 'middlename': <MatchFieldState.MATCH: 'match'>, 'lastname': <MatchFieldState.NOMATCH: 'nomatch'>, 'dayofbirth': <MatchFieldState.MATCH: 'match'>, 'monthofbirth': <MatchFieldState.MATCH: 'match'>, 'yearofbirth': <MatchFieldState.NOMATCH: 'nomatch'>, 'streetname': <MatchFieldState.MATCH: 'match'>, 'streetnumber': <MatchFieldState.MATCH: 'match'>, 'streettype': <MatchFieldState.MATCH: 'match'>, 'city': <MatchFieldState.MATCH: 'match'>, 'region': <MatchFieldState.NOMATCH: 'nomatch'>, 'postalcode': <MatchFieldState.NOMATCH: 'nomatch'>, 'unitnumber': <MatchFieldState.MATCH: 'match'>, 'address1': <MatchFieldState.NOMATCH: 'nomatch'>, 'taxid': <MatchFieldState.MISSING: 'missing'>, 'socialinsurancenumber': <MatchFieldState.MATCH: 'match'>, 'voterid': <MatchFieldState.NOMATCH: 'nomatch'>, 'gender': <MatchFieldState.NOMATCH: 'nomatch'>}, confidence=np.float64(0.808702458764489)), 'e': DataSourceResult(datasource_id='e', fields={'firstinitial': <MatchFieldState.MATCH: 'match'>, 'firstname': <MatchFieldState.NOMATCH: 'nomatch'>, 'middlename': <MatchFieldState.MATCH: 'match'>, 'lastname': <MatchFieldState.MATCH: 'match'>, 'dayofbirth': <MatchFieldState.NOMATCH: 'nomatch'>, 'monthofbirth': <MatchFieldState.MATCH: 'match'>, 'yearofbirth': <MatchFieldState.NOMATCH: 'nomatch'>, 'streetname': <MatchFieldState.MATCH: 'match'>, 'streetnumber': <MatchFieldState.NOMATCH: 'nomatch'>, 'streettype': <MatchFieldState.MATCH: 'match'>, 'city': <MatchFieldState.MATCH: 'match'>, 'region': <MatchFieldState.NOMATCH: 'nomatch'>, 'postalcode': <MatchFieldState.MATCH: 'match'>, 'unitnumber': <MatchFieldState.MATCH: 'match'>, 'address1': <MatchFieldState.NOMATCH: 'nomatch'>, 'taxid': <MatchFieldState.NOMATCH: 'nomatch'>, 'socialinsurancenumber': <MatchFieldState.MATCH: 'match'>, 'voterid': <MatchFieldState.NOMATCH: 'nomatch'>, 'gender': <MatchFieldState.MATCH: 'match'>}, confidence=np.float64(0.5369461449942549)), 'f': DataSourceResult(datasource_id='f', fields={'firstinitial': <MatchFieldState.NOMATCH: 'nomatch'>, 'firstname': <MatchFieldState.MATCH: 'match'>, 'middlename': <MatchFieldState.NOMATCH: 'nomatch'>, 'lastname': <MatchFieldState.MATCH: 'match'>, 'dayofbirth': <MatchFieldState.NOMATCH: 'nomatch'>, 'monthofbirth': <MatchFieldState.MATCH: 'match'>, 'yearofbirth': <MatchFieldState.MATCH: 'match'>, 'streetname': <MatchFieldState.MATCH: 'match'>, 'streetnumber': <MatchFieldState.NOMATCH: 'nomatch'>, 'streettype': <MatchFieldState.NOMATCH: 'nomatch'>, 'city': <MatchFieldState.MATCH: 'match'>, 'region': <MatchFieldState.NOMATCH: 'nomatch'>, 'postalcode': <MatchFieldState.MATCH: 'match'>, 'unitnumber': <MatchFieldState.MISSING: 'missing'>, 'address1': <MatchFieldState.NOMATCH: 'nomatch'>, 'taxid': <MatchFieldState.MATCH: 'match'>, 'socialinsurancenumber': <MatchFieldState.MATCH: 'match'>, 'voterid': <MatchFieldState.MATCH: 'match'>, 'gender': <MatchFieldState.MISSING: 'missing'>}, confidence=np.float64(0.6551408202161513)), 'g': DataSourceResult(datasource_id='g', fields={'firstinitial': <MatchFieldState.NOMATCH: 'nomatch'>, 'firstname': <MatchFieldState.MATCH: 'match'>, 'middlename': <MatchFieldState.MATCH: 'match'>, 'lastname': <MatchFieldState.MATCH: 'match'>, 'dayofbirth': <MatchFieldState.NOMATCH: 'nomatch'>, 'monthofbirth': <MatchFieldState.UNKNOWN: 'unknown'>, 'yearofbirth': <MatchFieldState.UNKNOWN: 'unknown'>, 'streetname': <MatchFieldState.UNKNOWN: 'unknown'>, 'streetnumber': <MatchFieldState.MATCH: 'match'>, 'streettype': <MatchFieldState.MATCH: 'match'>, 'city': <MatchFieldState.MATCH: 'match'>, 'region': <MatchFieldState.NOMATCH: 'nomatch'>, 'postalcode': <MatchFieldState.UNKNOWN: 'unknown'>, 'unitnumber': <MatchFieldState.UNKNOWN: 'unknown'>, 'address1': <MatchFieldState.MATCH: 'match'>, 'taxid': <MatchFieldState.MATCH: 'match'>, 'socialinsurancenumber': <MatchFieldState.MATCH: 'match'>, 'voterid': <MatchFieldState.MATCH: 'match'>, 'gender': <MatchFieldState.MATCH: 'match'>}, confidence=np.float64(0.5194531639840064)), 'h': DataSourceResult(datasource_id='h', fields={'firstinitial': <MatchFieldState.MATCH: 'match'>, 'firstname': <MatchFieldState.MISSING: 'missing'>, 'middlename': <MatchFieldState.NOMATCH: 'nomatch'>, 'lastname': <MatchFieldState.MISSING: 'missing'>, 'dayofbirth': <MatchFieldState.NOMATCH: 'nomatch'>, 'monthofbirth': <MatchFieldState.MATCH: 'match'>, 'yearofbirth': <MatchFieldState.NOMATCH: 'nomatch'>, 'streetname': <MatchFieldState.NOMATCH: 'nomatch'>, 'streetnumber': <MatchFieldState.NOMATCH: 'nomatch'>, 'streettype': <MatchFieldState.MATCH: 'match'>, 'city': <MatchFieldState.MATCH: 'match'>, 'region': <MatchFieldState.NOMATCH: 'nomatch'>, 'postalcode': <MatchFieldState.MATCH: 'match'>, 'unitnumber': <MatchFieldState.NOMATCH: 'nomatch'>, 'address1': <MatchFieldState.MATCH: 'match'>, 'taxid': <MatchFieldState.MATCH: 'match'>, 'socialinsurancenumber': <MatchFieldState.MATCH: 'match'>, 'voterid': <MatchFieldState.MISSING: 'missing'>, 'gender': <MatchFieldState.NOMATCH: 'nomatch'>}, confidence=np.float64(0.7776861889208992))})

In [18]:
sample_r = list(record.datasources.values())[0]
sample_r

DataSourceResult(datasource_id='a', fields={'firstinitial': <MatchFieldState.MATCH: 'match'>, 'firstname': <MatchFieldState.MATCH: 'match'>, 'middlename': <MatchFieldState.MATCH: 'match'>, 'lastname': <MatchFieldState.UNKNOWN: 'unknown'>, 'dayofbirth': <MatchFieldState.MATCH: 'match'>, 'monthofbirth': <MatchFieldState.MATCH: 'match'>, 'yearofbirth': <MatchFieldState.MATCH: 'match'>, 'streetname': <MatchFieldState.MATCH: 'match'>, 'streetnumber': <MatchFieldState.MATCH: 'match'>, 'streettype': <MatchFieldState.MATCH: 'match'>, 'city': <MatchFieldState.UNKNOWN: 'unknown'>, 'region': <MatchFieldState.MATCH: 'match'>, 'postalcode': <MatchFieldState.MATCH: 'match'>, 'unitnumber': <MatchFieldState.MATCH: 'match'>, 'address1': <MatchFieldState.UNKNOWN: 'unknown'>, 'taxid': <MatchFieldState.NOMATCH: 'nomatch'>, 'socialinsurancenumber': <MatchFieldState.NOMATCH: 'nomatch'>, 'voterid': <MatchFieldState.NOMATCH: 'nomatch'>, 'gender': <MatchFieldState.MATCH: 'match'>}, confidence=np.float64(0.5537621544721605))

In [19]:
sample_r.fields.keys()

dict_keys(['firstinitial', 'firstname', 'middlename', 'lastname', 'dayofbirth', 'monthofbirth', 'yearofbirth', 'streetname', 'streetnumber', 'streettype', 'city', 'region', 'postalcode', 'unitnumber', 'address1', 'taxid', 'socialinsurancenumber', 'voterid', 'gender'])

In [20]:
sample_r.confidence

np.float64(0.5537621544721605)

In [21]:
rule_1 = {
    "name": "rule_1",
    "op": "AND",
    "conditions": [
        {"field": "firstinitial", "check": "match"},
        {"field": "firstname", "check": "not_nomatch"},
        {"field": "lastname", "check": "match"},
    ]
}

In [22]:
rule_2 = {
    "name": "rule_2",
    "op": "AND",
    "conditions": [
        {"field": "firstname", "check": "match"},
        {"field": "lastname", "check": "match"},
        {
            "op": "OR",
            "conditions": [
                {"field": "city", "check": "match"},
                {"field": "postalcode", "check": "match"},
            ],
        },
    ],
}

In [23]:
rules = [rule_1, rule_2]

In [24]:
condition = {"field": "firstname", "check": "match"}

field = condition["field"]
check = condition["check"]

state = sample_r.fields.get(field, Models.MatchFieldState.MISSING)

state

In [25]:
if check == "match":
    result = state == Models.MatchFieldState.MATCH
elif check == "not_nomatch":
    result = state != Models.MatchFieldState.NOMATCH
else:
    raise ValueError(f"Unknown check type: {check}")

result

True

In [26]:
condition_results = []

for condition in rule_1["conditions"]:
    field = condition["field"]
    check = condition["check"]

    state = sample_r.fields.get(field, Models.MatchFieldState.MISSING)

    if check == "match":
        passed = state == Models.MatchFieldState.MATCH
    elif check == "not_nomatch":
        passed = state != Models.MatchFieldState.NOMATCH
    else:
        raise ValueError(f"Unknown check type: {check}")

    condition_results.append({
        "field": field,
        "check": check,
        "state": state.value,
        "passed": passed,
    })

condition_results

[{'field': 'firstinitial', 'check': 'match', 'state': 'match', 'passed': True},
 {'field': 'firstname',
  'check': 'not_nomatch',
  'state': 'match',
  'passed': True},
 {'field': 'lastname', 'check': 'match', 'state': 'unknown', 'passed': False}]

In [27]:
rule_1

{'name': 'rule_1',
 'op': 'AND',
 'conditions': [{'field': 'firstinitial', 'check': 'match'},
  {'field': 'firstname', 'check': 'not_nomatch'},
  {'field': 'lastname', 'check': 'match'}]}

In [28]:
def evaluate_rule(rule, datasource_result):
    if "field" in rule:
        field = rule["field"]
        check = rule["check"]

        state = datasource_result.fields.get(field, Models.MatchFieldState.MISSING)

        if check == "match":
            return state == Models.MatchFieldState.MATCH

        if check == "not_nomatch":
            return state != Models.MatchFieldState.NOMATCH

        raise ValueError(f"Unknown check type: {check}")

    op = rule["op"]
    conditions = rule["conditions"]

    if op == "AND":
        return all(evaluate_rule(child, datasource_result) for child in conditions)

    if op == "OR":
        return any(evaluate_rule(child, datasource_result) for child in conditions)

    raise ValueError(f"Unknown operator: {op}")

In [29]:
evaluate_rule(rule_1, sample_r)

False

In [30]:
record = records[0]

rule_results = {}

for rule in rules:
    rule_name = rule["name"]
    passing_datasources = []

    for datasource_id, datasource_result in record.datasources.items():
        passed = evaluate_rule(rule, datasource_result)

        if passed:
            passing_datasources.append(datasource_id)

    rule_results[rule_name] = passing_datasources

rule_results

{'rule_1': ['b', 'c'], 'rule_2': ['b', 'c', 'f', 'g']}

In [31]:
rule_names = list(rule_results.keys())
rule_names

['rule_1', 'rule_2']

In [32]:
used_partners = set()
assignment = {}
success = False

In [33]:
used_ds = set()
rule_assignment = {}
success = False


ecord = records[0]

rule_results = {}

for rule in rules:
    rule_name = rule["name"]
    passing_datasources = []

    for ds_id, ds_result in record.datasources.items():
        if evaluate_rule(rule, ds_result):
            passing_datasources.append(ds_id)

    rule_results[rule_name] = passing_datasources


rule_names = list(rule_results.keys())
used_partners = set()
assignment = {}


def find_valid_source_assignment(rule_index):

    if rule_index == len(rule_names):
        return True

    rule_name = rule_names[rule_index]
    ds_candidates = rule_results[rule_name]

    for ds in ds_candidates:
        if ds not in used_ds:
            rule_assignment[rule_name] = ds
            used_ds.add(ds)

            if find_valid_source_assignment(rule_index + 1):
                return True

            used_partners.remove(partner)
            del assignment[rule_name]

    return False


verified = find_valid_source_assignment(0)

{
    "record_id": record.record_id,
    "verified": verified,
    "rule_results": rule_results,
    "assignment": rule_assignment,
}

{'record_id': 'record_1',
 'verified': True,
 'rule_results': {'rule_1': ['b', 'c'], 'rule_2': ['b', 'c', 'f', 'g']},
 'assignment': {'rule_1': 'b', 'rule_2': 'c'}}

In [23]:
import sys
from pathlib import Path
import pickle
import pandas as pd

# add repo root to python path
sys.path.append(str(Path().resolve().parent))

import core.models as Models
import core.engine_processor as Engine

In [24]:
with open("../data/records.pkl", "rb") as f:
    records = pickle.load(f)

In [25]:
rule_1 = {
    "name": "rule_1",
    "op": "AND",
    "conditions": [
        {"field": "firstinitial", "check": "match"},
        {"field": "firstname", "check": "not_nomatch"},
        {"field": "lastname", "check": "match"},
    ]
}

In [26]:
rule_2 = {
    "name": "rule_2",
    "op": "AND",
    "conditions": [
        {"field": "firstname", "check": "match"},
        {"field": "lastname", "check": "match"},
        {
            "op": "OR",
            "conditions": [
                {"field": "city", "check": "match"},
                {"field": "postalcode", "check": "match"},
            ],
        },
    ],
}

In [27]:
rules = [rule_1, rule_2]

In [28]:
def evaluate_rule(rule, datasource_result):
    if "field" in rule:
        field = rule["field"]
        check = rule["check"]

        state = datasource_result.fields.get(field, Models.MatchFieldState.MISSING)

        if check == "match":
            return state == Models.MatchFieldState.MATCH

        if check == "not_nomatch":
            return state != Models.MatchFieldState.NOMATCH

        raise ValueError(f"Unknown check type: {check}")

    op = rule["op"]
    conditions = rule["conditions"]

    if op == "AND":
        return all(evaluate_rule(child, datasource_result) for child in conditions)

    if op == "OR":
        return any(evaluate_rule(child, datasource_result) for child in conditions)

    raise ValueError(f"Unknown operator: {op}")

In [29]:
    def find_valid_source_assignment(rule_index):

        if rule_index == len(rule_names):
            return True

        rule_name = rule_names[rule_index]
        ds_candidates = rule_results[rule_name]

        for ds in ds_candidates:
            if ds not in used_ds:
                rule_assignment[rule_name] = ds
                used_ds.add(ds)

                if find_valid_source_assignment(rule_index + 1):
                    return True

                used_partners.remove(partner)
                del assignment[rule_name]

        return False

In [30]:
outputs = []

for record in records[:10]:
    rule_results = {}

    for rule in rules:
        rule_name = rule["name"]
        passing_datasources = []

        for datasource_id, datasource_result in record.datasources.items():
            if evaluate_rule(rule, datasource_result):
                passing_datasources.append(datasource_id)

        rule_results[rule_name] = passing_datasources

    rule_names = list(rule_results.keys())
    used_ds= set()
    rule_assignment = {}

    verified = find_valid_source_assignment(0)

    outputs.append({
        "record_id": record.record_id,
        "verified": verified,
        "rule_results": rule_results,
        "rule_assignment": rule_assignment,
    })

In [31]:
outputs

[{'record_id': 'record_1',
  'verified': True,
  'rule_results': {'rule_1': ['b', 'c'], 'rule_2': ['b', 'c', 'f', 'g']},
  'rule_assignment': {'rule_1': 'b', 'rule_2': 'c'}},
 {'record_id': 'record_10',
  'verified': True,
  'rule_results': {'rule_1': ['a', 'd'], 'rule_2': ['d', 'f']},
  'rule_assignment': {'rule_1': 'a', 'rule_2': 'd'}},
 {'record_id': 'record_100',
  'verified': True,
  'rule_results': {'rule_1': ['a', 'b', 'd', 'e', 'f'],
   'rule_2': ['a', 'b', 'd']},
  'rule_assignment': {'rule_1': 'a', 'rule_2': 'b'}},
 {'record_id': 'record_1000',
  'verified': True,
  'rule_results': {'rule_1': ['a'], 'rule_2': ['c']},
  'rule_assignment': {'rule_1': 'a', 'rule_2': 'c'}},
 {'record_id': 'record_101',
  'verified': True,
  'rule_results': {'rule_1': ['g'], 'rule_2': ['c', 'd', 'e', 'h']},
  'rule_assignment': {'rule_1': 'g', 'rule_2': 'c'}},
 {'record_id': 'record_102',
  'verified': False,
  'rule_results': {'rule_1': [], 'rule_2': ['e']},
  'rule_assignment': {}},
 {'record_id': 'record_103',
  'verified': True,
  'rule_results': {'rule_1': ['a', 'b', 'd', 'f'],
   'rule_2': ['a', 'b', 'd', 'f', 'g']},
  'rule_assignment': {'rule_1': 'a', 'rule_2': 'b'}},
 {'record_id': 'record_104',
  'verified': True,
  'rule_results': {'rule_1': ['b'], 'rule_2': ['b', 'c']},
  'rule_assignment': {'rule_1': 'b', 'rule_2': 'c'}},
 {'record_id': 'record_105',
  'verified': True,
  'rule_results': {'rule_1': ['a', 'b'], 'rule_2': ['b', 'd']},
  'rule_assignment': {'rule_1': 'a', 'rule_2': 'b'}},
 {'record_id': 'record_106',
  'verified': True,
  'rule_results': {'rule_1': ['a', 'd'], 'rule_2': ['a', 'd']},
  'rule_assignment': {'rule_1': 'a', 'rule_2': 'd'}}]

In [32]:
summary_rows = []

for output in outputs:
    summary_rows.append({
        "record_id": output["record_id"],
        "verified": output["verified"],
        "rule_assignment": output["rule_assignment"],
        "rule_results": output["rule_results"],
    })

result_df = pd.DataFrame(summary_rows)

result_df

,record_id,verified,rule_assignment,rule_results
0,record_1,True,"{'rule_1': 'b', 'rule_2': 'c'}","{'rule_1': ['b', 'c'], 'rule_2': ['b', 'c', 'f..."
1,record_10,True,"{'rule_1': 'a', 'rule_2': 'd'}","{'rule_1': ['a', 'd'], 'rule_2': ['d', 'f']}"
2,record_100,True,"{'rule_1': 'a', 'rule_2': 'b'}","{'rule_1': ['a', 'b', 'd', 'e', 'f'], 'rule_2'..."
3,record_1000,True,"{'rule_1': 'a', 'rule_2': 'c'}","{'rule_1': ['a'], 'rule_2': ['c']}"
4,record_101,True,"{'rule_1': 'g', 'rule_2': 'c'}","{'rule_1': ['g'], 'rule_2': ['c', 'd', 'e', 'h']}"
5,record_102,False,{},"{'rule_1': [], 'rule_2': ['e']}"
6,record_103,True,"{'rule_1': 'a', 'rule_2': 'b'}","{'rule_1': ['a', 'b', 'd', 'f'], 'rule_2': ['a..."
7,record_104,True,"{'rule_1': 'b', 'rule_2': 'c'}","{'rule_1': ['b'], 'rule_2': ['b', 'c']}"
8,record_105,True,"{'rule_1': 'a', 'rule_2': 'b'}","{'rule_1': ['a', 'b'], 'rule_2': ['b', 'd']}"
9,record_106,True,"{'rule_1': 'a', 'rule_2': 'd'}","{'rule_1': ['a', 'd'], 'rule_2': ['a', 'd']}"