In [1]:
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv('../data/kyc_data.csv')
print(df.head())

   recordid datasource firstinitial firstname middlename lastname dayofbirth  \
0  record_1          a        match     match      match      NaN      match
1  record_1          b        match     match      match    match      match
2  record_1          c        match     match      match    match      match
3  record_1          d      nomatch     match      match  nomatch      match
4  record_1          e        match   nomatch      match    match    nomatch

  monthofbirth yearofbirth streetname  ...   city   region postalcode  \
0        match       match      match  ...    NaN    match      match
1      missing     missing      match  ...  match    match      match
2        match       match      match  ...  match  nomatch    nomatch
3        match     nomatch      match  ...  match  nomatch    nomatch
4        match     nomatch      match  ...  match  nomatch      match

  unitnumber address1    taxid socialinsurancenumber  voterid   gender  \
0      match      NaN  nomatch               nomatch  nomatch    match
1      match    match    match               nomatch    match    match
2    missing    match    match                 match    match  missing
3      match  nomatch  missing                 match  nomatch  nomatch
4      match  nomatch  nomatch                 match  nomatch    match

  trumatch_confidence
0            0.553762
1            0.568361
2            0.501050
3            0.808702
4            0.536946

[5 rows x 22 columns]

In [18]:
df

,recordid,datasource,firstinitial,firstname,middlename,lastname,dayofbirth,monthofbirth,yearofbirth,streetname,...,city,region,postalcode,unitnumber,address1,taxid,socialinsurancenumber,voterid,gender,trumatch_confidence
0,record_1,a,match,match,match,NaN,match,match,match,match,...,NaN,match,match,match,NaN,nomatch,nomatch,nomatch,match,0.553762
1,record_1,b,match,match,match,match,match,missing,missing,match,...,match,match,match,match,match,match,nomatch,match,match,0.568361
2,record_1,c,match,match,match,match,match,match,match,match,...,match,nomatch,nomatch,missing,match,match,match,match,missing,0.501050
3,record_1,d,nomatch,match,match,nomatch,match,match,nomatch,match,...,match,nomatch,nomatch,match,nomatch,missing,match,nomatch,nomatch,0.808702
4,record_1,e,match,nomatch,match,match,nomatch,match,nomatch,match,...,match,nomatch,match,match,nomatch,nomatch,match,nomatch,match,0.536946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,record_999,d,match,match,match,match,match,match,match,match,...,match,match,match,match,match,match,match,match,nomatch,0.566787
7996,record_999,e,nomatch,match,missing,match,match,nomatch,match,nomatch,...,match,match,match,match,match,match,match,nomatch,match,0.554050
7997,record_999,f,nomatch,match,missing,match,nomatch,match,match,match,...,nomatch,match,missing,nomatch,match,match,match,nomatch,match,0.470194
7998,record_999,g,nomatch,nomatch,NaN,NaN,matcha,matcha,matcha,matcha,...,NaN,nomatch,NaN,matcha,matcha,nomatch,match,match,nomatch,0.689957
7999,record_999,h,match,missing,missing,nomatch,nomatch,nomatch,missing,nomatch,...,nomatch,match,nomatch,nomatch,match,nomatch,match,nomatch,missing,0.741251

In [20]:
df.columns

Index(['recordid', 'datasource', 'firstinitial', 'firstname', 'middlename',
       'lastname', 'dayofbirth', 'monthofbirth', 'yearofbirth', 'streetname',
       'streetnumber', 'streettype', 'city', 'region', 'postalcode',
       'unitnumber', 'address1', 'taxid', 'socialinsurancenumber', 'voterid',
       'gender', 'trumatch_confidence'],
      dtype='str')

In [21]:
df_match_field = [ 'firstinitial', 'firstname', 'middlename',
       'lastname', 'dayofbirth', 'monthofbirth', 'yearofbirth', 'streetname',
       'streetnumber', 'streettype', 'city', 'region', 'postalcode',
       'unitnumber', 'address1', 'taxid', 'socialinsurancenumber', 'voterid',
       'gender']

In [22]:
set(df[df_match_field].values.flatten())

{'match', 'matcha', 'missing', nan, 'nomatch'}

In [23]:
df.replace('matcha', 'match', inplace=True)
df.replace(np.nan, 'unknown', inplace=True)

,recordid,datasource,firstinitial,firstname,middlename,lastname,dayofbirth,monthofbirth,yearofbirth,streetname,...,city,region,postalcode,unitnumber,address1,taxid,socialinsurancenumber,voterid,gender,trumatch_confidence
0,record_1,a,match,match,match,unknown,match,match,match,match,...,unknown,match,match,match,unknown,nomatch,nomatch,nomatch,match,0.553762
1,record_1,b,match,match,match,match,match,missing,missing,match,...,match,match,match,match,match,match,nomatch,match,match,0.568361
2,record_1,c,match,match,match,match,match,match,match,match,...,match,nomatch,nomatch,missing,match,match,match,match,missing,0.501050
3,record_1,d,nomatch,match,match,nomatch,match,match,nomatch,match,...,match,nomatch,nomatch,match,nomatch,missing,match,nomatch,nomatch,0.808702
4,record_1,e,match,nomatch,match,match,nomatch,match,nomatch,match,...,match,nomatch,match,match,nomatch,nomatch,match,nomatch,match,0.536946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,record_999,d,match,match,match,match,match,match,match,match,...,match,match,match,match,match,match,match,match,nomatch,0.566787
7996,record_999,e,nomatch,match,missing,match,match,nomatch,match,nomatch,...,match,match,match,match,match,match,match,nomatch,match,0.554050
7997,record_999,f,nomatch,match,missing,match,nomatch,match,match,match,...,nomatch,match,missing,nomatch,match,match,match,nomatch,match,0.470194
7998,record_999,g,nomatch,nomatch,unknown,unknown,match,match,match,match,...,unknown,nomatch,unknown,match,match,nomatch,match,match,nomatch,0.689957
7999,record_999,h,match,missing,missing,nomatch,nomatch,nomatch,missing,nomatch,...,nomatch,match,nomatch,nomatch,match,nomatch,match,nomatch,missing,0.741251

In [32]:
set(df[df_match_field].values.flatten())

{'match', 'missing', 'nomatch', 'unknown'}

In [27]:
df.sort_values('recordid', ascending=True)

,recordid,datasource,firstinitial,firstname,middlename,lastname,dayofbirth,monthofbirth,yearofbirth,streetname,...,city,region,postalcode,unitnumber,address1,taxid,socialinsurancenumber,voterid,gender,trumatch_confidence
0,record_1,a,match,match,match,unknown,match,match,match,match,...,unknown,match,match,match,unknown,nomatch,nomatch,nomatch,match,0.553762
1,record_1,b,match,match,match,match,match,missing,missing,match,...,match,match,match,match,match,match,nomatch,match,match,0.568361
2,record_1,c,match,match,match,match,match,match,match,match,...,match,nomatch,nomatch,missing,match,match,match,match,missing,0.501050
3,record_1,d,nomatch,match,match,nomatch,match,match,nomatch,match,...,match,nomatch,nomatch,match,nomatch,missing,match,nomatch,nomatch,0.808702
4,record_1,e,match,nomatch,match,match,nomatch,match,nomatch,match,...,match,nomatch,match,match,nomatch,nomatch,match,nomatch,match,0.536946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,record_999,d,match,match,match,match,match,match,match,match,...,match,match,match,match,match,match,match,match,nomatch,0.566787
7996,record_999,e,nomatch,match,missing,match,match,nomatch,match,nomatch,...,match,match,match,match,match,match,match,nomatch,match,0.554050
7997,record_999,f,nomatch,match,missing,match,nomatch,match,match,match,...,nomatch,match,missing,nomatch,match,match,match,nomatch,match,0.470194
7998,record_999,g,nomatch,nomatch,unknown,unknown,match,match,match,match,...,unknown,nomatch,unknown,match,match,nomatch,match,match,nomatch,0.689957
7999,record_999,h,match,missing,missing,nomatch,nomatch,nomatch,missing,nomatch,...,nomatch,match,nomatch,nomatch,match,nomatch,match,nomatch,missing,0.741251

In [29]:
df.recordid.value_counts().value_counts()

count
8    1000
Name: count, dtype: int64

In [30]:
len(set(df.recordid))

1000

In [31]:
df = pd.read_csv('../data/kyc_data.csv')
df.drop_duplicates(inplace=True)
df_match_field = [ 'firstinitial', 'firstname', 'middlename',
       'lastname', 'dayofbirth', 'monthofbirth', 'yearofbirth', 'streetname',
       'streetnumber', 'streettype', 'city', 'region', 'postalcode',
       'unitnumber', 'address1', 'taxid', 'socialinsurancenumber', 'voterid',
       'gender']
print(set(df[df_match_field].values.flatten()))
df.replace('matcha', 'match', inplace=True)
df.replace(np.nan, 'unknown', inplace=True)
df.recordid.value_counts().value_counts()

{'match', 'matcha', 'missing', nan, 'nomatch'}

count
8    1000
Name: count, dtype: int64