# processor

In [1]:
import pandas as pd
import numpy as np

In [34]:
df = pd.read_csv('../data/kyc_data.csv')
print(df.head())

   recordid datasource firstinitial firstname middlename lastname dayofbirth  \
0  record_1          a        match     match      match      NaN      match
1  record_1          b        match     match      match    match      match
2  record_1          c        match     match      match    match      match
3  record_1          d      nomatch     match      match  nomatch      match
4  record_1          e        match   nomatch      match    match    nomatch

  monthofbirth yearofbirth streetname  ...   city   region postalcode  \
0        match       match      match  ...    NaN    match      match
1      missing     missing      match  ...  match    match      match
2        match       match      match  ...  match  nomatch    nomatch
3        match     nomatch      match  ...  match  nomatch    nomatch
4        match     nomatch      match  ...  match  nomatch      match

  unitnumber address1    taxid socialinsurancenumber  voterid   gender  \
0      match      NaN  nomatch               nomatch  nomatch    match
1      match    match    match               nomatch    match    match
2    missing    match    match                 match    match  missing
3      match  nomatch  missing                 match  nomatch  nomatch
4      match  nomatch  nomatch                 match  nomatch    match

  trumatch_confidence
0            0.553762
1            0.568361
2            0.501050
3            0.808702
4            0.536946

[5 rows x 22 columns]

In [3]:
df

,recordid,datasource,firstinitial,firstname,middlename,lastname,dayofbirth,monthofbirth,yearofbirth,streetname,...,city,region,postalcode,unitnumber,address1,taxid,socialinsurancenumber,voterid,gender,trumatch_confidence
0,record_1,a,match,match,match,NaN,match,match,match,match,...,NaN,match,match,match,NaN,nomatch,nomatch,nomatch,match,0.553762
1,record_1,b,match,match,match,match,match,missing,missing,match,...,match,match,match,match,match,match,nomatch,match,match,0.568361
2,record_1,c,match,match,match,match,match,match,match,match,...,match,nomatch,nomatch,missing,match,match,match,match,missing,0.501050
3,record_1,d,nomatch,match,match,nomatch,match,match,nomatch,match,...,match,nomatch,nomatch,match,nomatch,missing,match,nomatch,nomatch,0.808702
4,record_1,e,match,nomatch,match,match,nomatch,match,nomatch,match,...,match,nomatch,match,match,nomatch,nomatch,match,nomatch,match,0.536946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,record_999,d,match,match,match,match,match,match,match,match,...,match,match,match,match,match,match,match,match,nomatch,0.566787
7996,record_999,e,nomatch,match,missing,match,match,nomatch,match,nomatch,...,match,match,match,match,match,match,match,nomatch,match,0.554050
7997,record_999,f,nomatch,match,missing,match,nomatch,match,match,match,...,nomatch,match,missing,nomatch,match,match,match,nomatch,match,0.470194
7998,record_999,g,nomatch,nomatch,NaN,NaN,matcha,matcha,matcha,matcha,...,NaN,nomatch,NaN,matcha,matcha,nomatch,match,match,nomatch,0.689957
7999,record_999,h,match,missing,missing,nomatch,nomatch,nomatch,missing,nomatch,...,nomatch,match,nomatch,nomatch,match,nomatch,match,nomatch,missing,0.741251

In [4]:
df.columns

Index(['recordid', 'datasource', 'firstinitial', 'firstname', 'middlename',
       'lastname', 'dayofbirth', 'monthofbirth', 'yearofbirth', 'streetname',
       'streetnumber', 'streettype', 'city', 'region', 'postalcode',
       'unitnumber', 'address1', 'taxid', 'socialinsurancenumber', 'voterid',
       'gender', 'trumatch_confidence'],
      dtype='str')

In [5]:
df_match_field = [ 'firstinitial', 'firstname', 'middlename',
       'lastname', 'dayofbirth', 'monthofbirth', 'yearofbirth', 'streetname',
       'streetnumber', 'streettype', 'city', 'region', 'postalcode',
       'unitnumber', 'address1', 'taxid', 'socialinsurancenumber', 'voterid',
       'gender']

In [6]:
set(df[df_match_field].values.flatten())

{'match', 'matcha', 'missing', nan, 'nomatch'}

In [7]:
df.replace('matcha', 'match', inplace=True)
df.replace(np.nan, 'unknown', inplace=True)

,recordid,datasource,firstinitial,firstname,middlename,lastname,dayofbirth,monthofbirth,yearofbirth,streetname,...,city,region,postalcode,unitnumber,address1,taxid,socialinsurancenumber,voterid,gender,trumatch_confidence
0,record_1,a,match,match,match,unknown,match,match,match,match,...,unknown,match,match,match,unknown,nomatch,nomatch,nomatch,match,0.553762
1,record_1,b,match,match,match,match,match,missing,missing,match,...,match,match,match,match,match,match,nomatch,match,match,0.568361
2,record_1,c,match,match,match,match,match,match,match,match,...,match,nomatch,nomatch,missing,match,match,match,match,missing,0.501050
3,record_1,d,nomatch,match,match,nomatch,match,match,nomatch,match,...,match,nomatch,nomatch,match,nomatch,missing,match,nomatch,nomatch,0.808702
4,record_1,e,match,nomatch,match,match,nomatch,match,nomatch,match,...,match,nomatch,match,match,nomatch,nomatch,match,nomatch,match,0.536946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,record_999,d,match,match,match,match,match,match,match,match,...,match,match,match,match,match,match,match,match,nomatch,0.566787
7996,record_999,e,nomatch,match,missing,match,match,nomatch,match,nomatch,...,match,match,match,match,match,match,match,nomatch,match,0.554050
7997,record_999,f,nomatch,match,missing,match,nomatch,match,match,match,...,nomatch,match,missing,nomatch,match,match,match,nomatch,match,0.470194
7998,record_999,g,nomatch,nomatch,unknown,unknown,match,match,match,match,...,unknown,nomatch,unknown,match,match,nomatch,match,match,nomatch,0.689957
7999,record_999,h,match,missing,missing,nomatch,nomatch,nomatch,missing,nomatch,...,nomatch,match,nomatch,nomatch,match,nomatch,match,nomatch,missing,0.741251

In [8]:
set(df[df_match_field].values.flatten())

{'match', 'missing', 'nomatch', 'unknown'}

In [9]:
df.sort_values('recordid', ascending=True)

,recordid,datasource,firstinitial,firstname,middlename,lastname,dayofbirth,monthofbirth,yearofbirth,streetname,...,city,region,postalcode,unitnumber,address1,taxid,socialinsurancenumber,voterid,gender,trumatch_confidence
0,record_1,a,match,match,match,unknown,match,match,match,match,...,unknown,match,match,match,unknown,nomatch,nomatch,nomatch,match,0.553762
1,record_1,b,match,match,match,match,match,missing,missing,match,...,match,match,match,match,match,match,nomatch,match,match,0.568361
2,record_1,c,match,match,match,match,match,match,match,match,...,match,nomatch,nomatch,missing,match,match,match,match,missing,0.501050
3,record_1,d,nomatch,match,match,nomatch,match,match,nomatch,match,...,match,nomatch,nomatch,match,nomatch,missing,match,nomatch,nomatch,0.808702
4,record_1,e,match,nomatch,match,match,nomatch,match,nomatch,match,...,match,nomatch,match,match,nomatch,nomatch,match,nomatch,match,0.536946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,record_999,d,match,match,match,match,match,match,match,match,...,match,match,match,match,match,match,match,match,nomatch,0.566787
7996,record_999,e,nomatch,match,missing,match,match,nomatch,match,nomatch,...,match,match,match,match,match,match,match,nomatch,match,0.554050
7997,record_999,f,nomatch,match,missing,match,nomatch,match,match,match,...,nomatch,match,missing,nomatch,match,match,match,nomatch,match,0.470194
7998,record_999,g,nomatch,nomatch,unknown,unknown,match,match,match,match,...,unknown,nomatch,unknown,match,match,nomatch,match,match,nomatch,0.689957
7999,record_999,h,match,missing,missing,nomatch,nomatch,nomatch,missing,nomatch,...,nomatch,match,nomatch,nomatch,match,nomatch,match,nomatch,missing,0.741251

In [10]:
df.recordid.value_counts().value_counts()

count
8    1000
Name: count, dtype: int64

In [11]:
len(set(df.recordid))

1000

In [12]:
df = pd.read_csv('../data/kyc_data.csv')
df.drop_duplicates(inplace=True)
df_match_field = [ 'firstinitial', 'firstname', 'middlename',
       'lastname', 'dayofbirth', 'monthofbirth', 'yearofbirth', 'streetname',
       'streetnumber', 'streettype', 'city', 'region', 'postalcode',
       'unitnumber', 'address1', 'taxid', 'socialinsurancenumber', 'voterid',
       'gender']
print(set(df[df_match_field].values.flatten()))
df.replace('matcha', 'match', inplace=True)
df.replace(np.nan, 'unknown', inplace=True)
df.recordid.value_counts().value_counts()

{'missing', nan, 'nomatch', 'matcha', 'match'}

count
8    1000
Name: count, dtype: int64

In [31]:
rule_names = list(rule_results.keys())
rule_names

['rule_1', 'rule_2']

## Evaluator

In [2]:
import sys
from pathlib import Path
import pickle
import pandas as pd

# add repo root to python path
sys.path.append(str(Path().resolve().parent))

import core.models as Models
import core.engine_processor as Engine

with open("../data/records.pkl", "rb") as f:
    records = pickle.load(f)


rule_1 = {
    "name": "rule_1",
    "op": "AND",
    "conditions": [
        {"field": "firstinitial", "check": "match"},
        {"field": "firstname", "check": "not_nomatch"},
        {"field": "lastname", "check": "match"},
    ]
}

rule_2 = {
    "name": "rule_2",
    "op": "AND",
    "conditions": [
        {"field": "firstname", "check": "match"},
        {"field": "lastname", "check": "match"},
        {
            "op": "OR",
            "conditions": [
                {"field": "city", "check": "match"},
                {"field": "postalcode", "check": "match"},
            ],
        },
    ],
}

rules = [rule_1, rule_2]

def evaluate_rule(rule, datasource_result):
    if "field" in rule:
        field = rule["field"]
        check = rule["check"]

        state = datasource_result.fields.get(field, Models.MatchFieldState.MISSING)

        if check == "match":
            return state == Models.MatchFieldState.MATCH

        if check == "not_nomatch":
            return state != Models.MatchFieldState.NOMATCH

        raise ValueError(f"Unknown check type: {check}")

    op = rule["op"]
    conditions = rule["conditions"]

    if op == "AND":
        return all(evaluate_rule(child, datasource_result) for child in conditions)

    if op == "OR":
        return any(evaluate_rule(child, datasource_result) for child in conditions)

    raise ValueError(f"Unknown operator: {op}")


def find_valid_source_assignment(rule_index):

    if rule_index == len(rule_names):
        return True

    rule_name = rule_names[rule_index]
    ds_candidates = rule_results[rule_name]

    for ds in ds_candidates:
        if ds not in used_ds:
            rule_assignment[rule_name] = ds
            used_ds.add(ds)

            if find_valid_source_assignment(rule_index + 1):
                return True

            used_ds.remove(ds)
            del rule_assignment[rule_name]

    return False


outputs = []

for record in records[:500]:
    rule_results = {}

    for rule in rules:
        rule_name = rule["name"]
        passing_datasources = []

        for datasource_id, datasource_result in record.datasources.items():
            if evaluate_rule(rule, datasource_result):
                passing_datasources.append(datasource_id)

        rule_results[rule_name] = passing_datasources

    rule_names = list(rule_results.keys())
    used_ds= set()
    rule_assignment = {}

    verified = find_valid_source_assignment(0)

    outputs.append({
        "record_id": record.record_id,
        "verified": verified,
        "rule_results": rule_results,
        "rule_assignment": rule_assignment,
    })

summary_rows = []

for output in outputs:
    summary_rows.append({
        "record_id": output["record_id"],
        "verified": output["verified"],
        "rule_assignment": output["rule_assignment"],
        "rule_results": output["rule_results"],
    })

result_df = pd.DataFrame(summary_rows)

result_df

,record_id,verified,rule_assignment,rule_results
0,record_1,True,"{'rule_1': 'b', 'rule_2': 'c'}","{'rule_1': ['b', 'c'], 'rule_2': ['b', 'c', 'f..."
1,record_10,True,"{'rule_1': 'a', 'rule_2': 'd'}","{'rule_1': ['a', 'd'], 'rule_2': ['d', 'f']}"
2,record_100,True,"{'rule_1': 'a', 'rule_2': 'b'}","{'rule_1': ['a', 'b', 'd', 'e', 'f'], 'rule_2'..."
3,record_1000,True,"{'rule_1': 'a', 'rule_2': 'c'}","{'rule_1': ['a'], 'rule_2': ['c']}"
4,record_101,True,"{'rule_1': 'g', 'rule_2': 'c'}","{'rule_1': ['g'], 'rule_2': ['c', 'd', 'e', 'h']}"
...,...,...,...,...
495,record_544,True,"{'rule_1': 'a', 'rule_2': 'b'}","{'rule_1': ['a', 'b'], 'rule_2': ['a', 'b']}"
496,record_545,True,"{'rule_1': 'a', 'rule_2': 'b'}","{'rule_1': ['a'], 'rule_2': ['a', 'b', 'd']}"
497,record_546,True,"{'rule_1': 'b', 'rule_2': 'd'}","{'rule_1': ['b'], 'rule_2': ['d']}"
498,record_547,False,{},"{'rule_1': ['c'], 'rule_2': ['c']}"
499,record_548,True,"{'rule_1': 'd', 'rule_2': 'b'}","{'rule_1': ['d', 'g'], 'rule_2': ['b', 'g']}"

In [1]:
import sys
from pathlib import Path
import pickle
import pandas as pd

# add repo root to python path
sys.path.append(str(Path().resolve().parent))

import core.models as Models
import core.engine_processor as Engine

In [2]:
with open("../data/records.pkl", "rb") as f:
    records = pickle.load(f)

In [ ]:
rule_1 = {
    "name": "rule_1",
    "op": "AND",
    "conditions": [
        {"field": "firstinitial", "check": "match"},
        {"field": "firstname", "check": "not_nomatch"},
        {"field": "lastname", "check": "match"},
    ]
}

rule_2 = {
    "name": "rule_2",
    "op": "AND",
    "conditions": [
        {"field": "firstname", "check": "match"},
        {"field": "lastname", "check": "match"},
        {
            "op": "OR",
            "conditions": [
                {"field": "city", "check": "match"},
                {"field": "postalcode", "check": "match"},
            ],
        },
    ],
}

rules = [rule_1, rule_2]

In [6]:
def evaluate_rule(rule, datasource_result):
    if "field" in rule:
        field = rule["field"]
        check = rule["check"]

        state = datasource_result.fields.get(field, Models.MatchFieldState.MISSING)

        if check == "match":
            return state == Models.MatchFieldState.MATCH

        if check == "not_nomatch":
            return state != Models.MatchFieldState.NOMATCH

        raise ValueError(f"Unknown check type: {check}")

    op = rule["op"]
    conditions = rule["conditions"]

    if op == "AND":
        return all(evaluate_rule(child, datasource_result) for child in conditions)

    if op == "OR":
        return any(evaluate_rule(child, datasource_result) for child in conditions)

    raise ValueError(f"Unknown operator: {op}")

In [9]:
def find_valid_source_assignment(rule_index):

    if rule_index == len(rule_names):
        return True

    rule_name = rule_names[rule_index]
    ds_candidates = rule_results[rule_name]

    for ds in ds_candidates:
        if ds not in used_ds:
            rule_assignment[rule_name] = ds
            used_ds.add(ds)

            if find_valid_source_assignment(rule_index + 1):
                return True

            used_ds.remove(ds)
            del rule_assignment[rule_name]

    return False

In [10]:
outputs = []

for record in records[:500]:
    rule_results = {}

    for rule in rules:
        rule_name = rule["name"]
        passing_datasources = []

        for datasource_id, datasource_result in record.datasources.items():
            if evaluate_rule(rule, datasource_result):
                passing_datasources.append(datasource_id)

        rule_results[rule_name] = passing_datasources

    rule_names = list(rule_results.keys())
    used_ds= set()
    rule_assignment = {}

    verified = find_valid_source_assignment(0)

    outputs.append({
        "record_id": record.record_id,
        "verified": verified,
        "rule_results": rule_results,
        "rule_assignment": rule_assignment,
    })

In [11]:
summary_rows = []

for output in outputs:
    summary_rows.append({
        "record_id": output["record_id"],
        "verified": output["verified"],
        "rule_assignment": output["rule_assignment"],
        "rule_results": output["rule_results"],
    })

result_df = pd.DataFrame(summary_rows)

result_df

,record_id,verified,rule_assignment,rule_results
0,record_1,True,"{'rule_1': 'b', 'rule_2': 'c'}","{'rule_1': ['b', 'c'], 'rule_2': ['b', 'c', 'f..."
1,record_10,True,"{'rule_1': 'a', 'rule_2': 'd'}","{'rule_1': ['a', 'd'], 'rule_2': ['d', 'f']}"
2,record_100,True,"{'rule_1': 'a', 'rule_2': 'b'}","{'rule_1': ['a', 'b', 'd', 'e', 'f'], 'rule_2'..."
3,record_1000,True,"{'rule_1': 'a', 'rule_2': 'c'}","{'rule_1': ['a'], 'rule_2': ['c']}"
4,record_101,True,"{'rule_1': 'g', 'rule_2': 'c'}","{'rule_1': ['g'], 'rule_2': ['c', 'd', 'e', 'h']}"
...,...,...,...,...
495,record_544,True,"{'rule_1': 'a', 'rule_2': 'b'}","{'rule_1': ['a', 'b'], 'rule_2': ['a', 'b']}"
496,record_545,True,"{'rule_1': 'a', 'rule_2': 'b'}","{'rule_1': ['a'], 'rule_2': ['a', 'b', 'd']}"
497,record_546,True,"{'rule_1': 'b', 'rule_2': 'd'}","{'rule_1': ['b'], 'rule_2': ['d']}"
498,record_547,False,{},"{'rule_1': ['c'], 'rule_2': ['c']}"
499,record_548,True,"{'rule_1': 'd', 'rule_2': 'b'}","{'rule_1': ['d', 'g'], 'rule_2': ['b', 'g']}"